### ISSUE TITLE
Graph representations

### ISSUE THREAD

**Issue by lassik** [enragedginger/tensorflow-clj#2]
We can make a graph from scratch using the Java API. However, it's not a great fit for rhe Clojure way of thinking. Graph operations are by opaque Java objects, not transparent Clojure values. Also, to make an operation object you need to give it the Graph it will go into - it doesn't seem possible to create free-standing operations and add them to a graph later. That's not very composable. And of course adding an operation to a graph mutates both the operation and the graph.

The Graph class has a method that loads a graph from a Protocol Buffers description. It could be a better approach for Clojure to forgo the graph builder API entirely and just load graphs. We could devise an idiomatic DSL to compose graphs into a representation built out of nested maps and vectors. Then have a function that converts that repr into Protocol Buffers for loading. We would also gain the ability to transfer graphs both ways between Clojure and Python, provided the file format is eventually stable.

**Comment by enragedginger** [comment]
That makes sense to me. What are the pros and cons of each approach?

**Comment by lassik** [comment]
Converting our own graph DSL to Protocol Buffers then loading it:
+ More composable
+ Easier to manage resources (Java objects)
+ Lisp is a perfect fir for DSLs
+ Can export models from Clojure to Python
- We have to invent our own DSL that doesn't look like TensorFlow Python code.

Using the graph builder API:
+ Looks roughly like the Python TensorFlow API
- Java API Lags behind Python in features
- Resource management is more complex
- Cannot export models from Clojure to Python

**Comment by enragedginger** [comment]
Okay, I think I see what you're getting at. Originally, my goal with this library was to wrap some future Java API in an idiomatic Clojure way. So, if we build our own DSL for creating graphs via protobuff, will we have to hit the C bindings directly, or will we be able to somehow use the Java API?

**Comment by lassik** [comment]
Converting our own graph DSL to Protocol Buffers then loading it:
+ More composable
+ Easier to manage resources (Java objects)
+ Lisp is a perfect fir for DSLs
+ Can export models from Clojure to Python
- We have to invent our own DSL that doesn't look like TensorFlow Python code.

Using the graph builder API:
+ Looks roughly like the Python TensorFlow API
- Java API Lags behind Python in features
- Resource management is more complex
- Cannot export models from Clojure to Python

**Comment by lassik** [comment]
The Java API has an `importGraphDef()` method that takes a graph dump from Python as `byte[]`. So we'd simply need to learn how to construct a suitable `byte[]` from our DSL. If that doesn't work out my Plan B would be to just go with the official Java graph builder API (which calls C/C++ via JNI under the hood).

**Comment by enragedginger** [comment]
Okay. So we would essentially build the graphs in Clojure using composable functions, convert the results to byte arrays using protobuf, and then read that back in with the Java API? From there, I assume we would just wrap the functionality that we need in the Java API from Clojure, or is there a better way to do this?

**Comment by lassik** [comment]
Exactly :) The main point is we'd we only need to wrap a few of the simplest API functions to load and run the graph instead of wrapping the entire API. (The graph-building classes and methods seem to be by far its biggest and most intricate part, and based on object-oriented instead of functional principles.)

**Comment by enragedginger** [comment]
Cool. I think that all makes sense to me. I'll try to hack something together over the course of the next week. If you happen to get something up and running before then, just push it out to a branch and we'll collaborate on it. Thanks for your interest in this project!

**Comment by lassik** [comment]
Great. Got the loading to work: #4 Still need to investigate the crash.
