### ISSUE TITLE
Installing TensorFlow

### ISSUE THREAD

**Issue by lassik** [enragedginger/tensorflow-clj#3]
I don't think you need to install anything via the OS package manager. The guide <https://www.tensorflow.org/versions/master/install/install_java> simply says you need to add the JAR dependency to Maven. I had the same experience using Leiningen instead of Maven - it was enough to add the dependency. I tried installing and un-installing `libtensorflow` via Homebrew and it didn't seem to make a difference as to its availability on the JVM.

**Comment by enragedginger** [comment]
Are you referring to the Travis build failures? Also, are you on `clojurians.slack.com`? If so, I think that will be easier for communication than GitHub issues for now.

**Comment by lassik** [comment]
Yes, referring to Travis right now, but also intended as a more general remark. We could use this thread to try and map out how to install TF on every platform where Clojure runs. Hopefully it's as simple as telling Leiningen to use it ;) I signed up to Slack as @lassik
